version: '2.1'
services:
  customer:
    image: 'hm716/customer:latest'
    container_name: customer
    #restart: always
#    build: ../customer
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"


  account:
    image: 'hm716/account:latest'
    container_name: account
    #restart: always
#    build: ../account
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8085:8085"

  credit:
    image: 'hm716/credit:latest'
    container_name : credit
#    build: ../credit
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8090:8090"



  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testtesttest

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5




